/**
 * 通用视觉生成运行时规则。
 * 规则只描述跨行业稳定约束，不包含任何行业、人物、地点或商品模板。
 */

module.exports = [
  {
    id: 'kb_runtime_person_visual_contract_v1',
    collection: 'engineering',
    subcategory: '知识驱动生成',
    title: '人物视觉合同运行时规则',
    summary: '将已批准身份、身材、妆发、服装和配件清单作为跨视图不可变量。',
    content: '适用于任意合法行业与人物类型。只允许当前生成单元明确要求的角度、表情或动作发生变化。',
    tags: ['运行时规则', '人物一致性', '行业无关'],
    keywords: ['person contract', 'identity invariants', 'knowledge policy'],
    prompt_snippets: [],
    applies_to: ['character_consistency', 'prompt_engineer', 'director', 'test_engineer'],
    source: 'VIDO 人物档案与一致性回归经验，2026-08-06',
    lang: 'zh-en',
    enabled: true,
    runtime_policy: {
      schema_version: 1,
      rules: [{
        id: 'person-closed-visual-inventory', version: 1, status: 'active', priority: 90,
        stages: ['person_dossier', 'keyframe'], asset_types: ['person'], enforcement: 'hard',
        conflict_key: 'person_visual_inventory',
        instruction: 'Treat the approved identity, apparent age, body proportions, hair, makeup, wardrobe, footwear and wearable-accessory inventory as a closed visual contract. Change only the view, expression or action explicitly requested by the current unit; never add, remove or redesign an invariant.',
        negative: 'unrequested identity, age, body, hair, makeup, wardrobe, footwear or wearable-accessory change',
        qa_checks: ['visible person invariants match the approved contract', 'only the authored view, expression or action changes'],
      }],
    },
  },
  {
    id: 'kb_runtime_scene_visual_contract_v1',
    collection: 'engineering',
    subcategory: '知识驱动生成',
    title: '场景物理合同与多尺度场景卡运行时规则',
    summary: '锁定空间、材质、灯光和禁止项，并用总览、关系、局部、细节四级证据约束跨镜一致性。',
    content: '场景知识只能结构化任务已有事实：把同一场景拆为稳定空间骨架、资产清单、环境状态、材质细节和色彩锚点，再按总览到细节的尺度梯度生成与验收；不得依据行业印象增加未要求的内容。',
    tags: ['运行时规则', '场景一致性', '行业无关'],
    keywords: ['scene contract', 'physical invariants', 'knowledge policy'],
    prompt_snippets: [],
    applies_to: ['art_director', 'atmosphere', 'prompt_engineer', 'director', 'test_engineer'],
    source: 'VIDO 多场景空间合同与跨视图回归经验，2026-08-06',
    lang: 'zh-en',
    enabled: true,
    runtime_policy: {
      schema_version: 1,
      rules: [{
        id: 'scene-task-facts-only', version: 1, status: 'active', priority: 90,
        stages: ['scene_asset', 'keyframe'], asset_types: ['scene'], enforcement: 'hard',
        conflict_key: 'scene_scope_authority',
        instruction: 'Keep layout, boundaries, access points, material identity, lighting logic, interaction zones and explicit exclusions as separate physical invariants. Use only current-task evidence; never infer industry-standard furniture, decoration, people, products or segmentation that the task did not request.',
        negative: 'generic industry template, unrequested structure, furnishing, decoration, person, product or surface segmentation',
        qa_checks: ['layout, material, lighting and interaction evidence match current-task facts', 'no industry stereotype or unrequested element is introduced'],
      }, {
        id: 'scene-task-facts-only', version: 2, status: 'active', priority: 90,
        stages: ['scene_asset', 'keyframe'], asset_types: ['scene'], enforcement: 'hard',
        conflict_key: 'scene_scope_authority',
        instruction: 'Represent the current-task scene as one scale-linked evidence card: overview silhouette and boundaries; spatial relationships, access points and camera anchors; local interaction zones and asset groups; material, weathering, atmosphere and small-detail evidence. Keep one stable geometry, asset inventory, environmental state, lighting logic and palette anchor across all scales and views. Include only evidence authorized by the task.',
        negative: 'inconsistent geometry or scale, missing or duplicated task-authorized asset, drifting weather, material, lighting or palette, generic industry template, or unrequested structure, furnishing, decoration, person or product',
        qa_checks: ['overview, relationship, local and detail views describe the same physical scene', 'geometry, asset inventory, environmental state, material, lighting and palette anchors remain consistent across scales', 'no task-authorized asset disappears or duplicates and no unrequested element is introduced'],
      }],
    },
  },
  {
    id: 'kb_runtime_keyframe_visual_contract_v1',
    collection: 'engineering',
    subcategory: '知识驱动生成',
    title: '关键帧最小变化运行时规则',
    summary: '关键帧只执行当前镜头明确要求的可见变化，并保持人物、商品和场景锁。',
    content: '镜头构图不能成为重建人物、商品或场景的理由；静态关键帧不承担视频时间变化的证明责任。',
    tags: ['运行时规则', '关键帧', '最小变化'],
    keywords: ['keyframe contract', 'intended change', 'invariants'],
    prompt_snippets: [],
    applies_to: ['storyboard', 'director', 'prompt_engineer', 'test_engineer'],
    source: 'VIDO 关键帧合同与时序证据回归经验，2026-08-06',
    lang: 'zh-en',
    enabled: true,
    runtime_policy: {
      schema_version: 1,
      rules: [{
        id: 'keyframe-minimum-authored-change', version: 1, status: 'active', priority: 92,
        stages: ['keyframe'], asset_types: ['shot'], enforcement: 'hard',
        conflict_key: 'keyframe_change_boundary',
        instruction: 'Render only the visible state and composition authored for this shot. Preserve every verified person, product and scene invariant; a new camera composition does not authorize redesigning locked assets. Do not require a still keyframe to prove temporal motion or transition timing.',
        negative: 'asset redesign, unrequested visible state, temporal effect baked into a still frame',
        qa_checks: ['the authored visible state is present', 'verified person, product and scene locks remain unchanged', 'temporal-only effects are not judged in the still frame'],
      }],
    },
  },
  {
    id: 'kb_runtime_video_temporal_contract_v1',
    collection: 'engineering',
    subcategory: '知识驱动生成',
    title: '视频时序与物理运行时规则',
    summary: '视频从已批准关键帧出发，只执行镜头动作，并以可见因果结果结束。',
    content: '适用于任意行业和场景；不规定具体人物、产品、地点或动作，只规定时序、物理与资产连续性。',
    tags: ['运行时规则', '视频连续性', '物理合理性', '行业无关'],
    keywords: ['video contract', 'temporal stability', 'physical causality'],
    prompt_snippets: [],
    applies_to: ['director', 'storyboard', 'prompt_engineer', 'test_engineer'],
    source: 'VIDO 视频抽帧、跨镜连续性与物理 QA 经验，2026-08-06',
    lang: 'zh-en',
    enabled: true,
    runtime_policy: {
      schema_version: 1,
      rules: [{
        id: 'video-keyframe-causal-continuity', version: 1, status: 'active', priority: 94,
        stages: ['video'], asset_types: ['shot'], enforcement: 'hard',
        conflict_key: 'video_temporal_boundary',
        instruction: 'Start from the approved keyframe state, perform only the authored action and camera movement, and reach the declared end state through physically plausible intermediate motion. Preserve identity, wardrobe, product, material, geometry and lighting without flicker, duplication, morphing or teleportation.',
        negative: 'flicker, identity drift, wardrobe drift, product drift, geometry drift, duplication, morphing, teleportation or causally unsupported end state',
        qa_checks: ['start, middle and end visibly prove the authored causal progression', 'identity, product, scene, material and lighting remain temporally stable', 'contacts, mass and anatomy remain physically plausible'],
      }],
    },
  },
];
